{
    "version": "2",
    "services": {
        "app": {
            "image": "mhart/alpine-node",
            "command": [
                "npm",
                "start"
            ],
            "working_dir": "/app/",
            "volumes": [
                "./:/app"
            ],
            "expose": [
                "80"
            ],
            "depends_on": [
                "rethinkdb",
                "rabbitmq"
            ],
            "restart": "unless-stopped"
        },
        "rabbitmq": {
          "image": "smebberson/alpine-rabbitmq",
          "environment": {
            "RABBITMQ_DEFAULT_VHOST": "/",
            "RABBITMQ_USER": "admin",
            "RABBITMQ_ENABLE_MANAGEMENT_PLUGIN": "true"
          },
          "volumes": [
            "./data/queue:/data/rabbitmq/mnesia"
          ],
          "ports": [
            "54323:15672"
          ],
          "restart": "unless-stopped"
        },

        "rethinkdb": {
          "image": "rethinkdb:2.3.5",
          "volumes": [
              "./data/db:/data:rw"
          ],
          "expose": [
            "28015",
            "8080"
          ],
          "restart": "unless-stopped"
        },
        "nginx": {
            "image": "nginx:1.11.4-alpine",
            "volumes": [
                "./src/config/nginx.conf:/etc/nginx/nginx.conf:ro",
                "./src/config/.htpasswd:/etc/nginx/.htpasswd:ro",
                "./src/swagger.json:/mnt/swagger/swagger.json:ro"
            ],
            "ports": [
                "54321:54321",
                "54322:8080"
            ],
            "depends_on": [
                "app",
                "swagger-ui"
            ],
            "restart": "unless-stopped"
        },
        "swagger-ui": {
            "image": "schickling/swagger-ui",
            "environment": {
                "API_URL": "/swagger.json"
            },
            "expose": [
                "80"
            ],
            "restart": "unless-stopped"
        }
    }
}
